In [131]:
import pandas as pd
import re
import numpy as np

In [132]:
with open ('/Users/tkoti/LabWork/FlyntLab/AutoDeep/testing/Pomonella/mirdeep_Pomonella/output.mrd') as f:
    read_data = f.read().splitlines()

In [133]:
read_data

['>QFTL02000023.1_11538',
 'score total\t\t      369501.7',
 'score for star read(s)\t           3.9',
 'score for read counts\t      369494.9',
 'score for mfe\t\t           1.9',
 'score for randfold\t           1.6',
 'score for cons. seed\t          -0.6',
 'total read count\t        724760',
 'mature read count\t        718682',
 'loop read count\t\t 0',
 'star read count\t\t          6078',
 'exp                           ffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSllllllllllllMMMMMMMMMMMMMMMMMMMMMMffffffffffffffffffff',
 'obs                           ffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSllllllllllllMMMMMMMMMMMMMMMMMMMMMMffffffffffffffffffff',
 'pri_seq                       gucagaagacuguuucgccaccuggugauugccacuagcgagguauagaguuccuacguauauuggccuguaggaacuucauaccgugcucuuggguuugccaaucuucuac',
 'pri_struct                    ...((((((.((..(((((....)))))...(((..((((.(((((..((((((((((..........))))))))))..))))).))))..)))......)).))))))..\t#MM',
 'seq_57026257_x1               ..................caccuggugauugccacu............................................................................\t0',
 'seq_55564128_x2               ..........................gauugccacuagcgagguauagaguu............................................................\t0',
 'seq_53349098_x3               .................................Ucuagcgagguauagaguuccuacg......................................................\t1',
 'seq_57407504_x1               ...................................Cagcgagguauagaguuccuacg......................................................\t1',
 'seq_53144687_x3               ...................................uagcgagguauagaguuccuacg......................................................\t0',
 'seq_49922967_x7               ....................................agcgagguauagaguucc..........................................................\t0',
 'seq_57004160_x1               ....................................agcgagguauagaguAccu.........................................................\t1',
 'seq_41227162_x45              ....................................agcgagguauagaguuccu.........................................................\t0',
 'seq_57936952_x1               ....................................aUcgagguauagaguuccua........................................................\t1',
 'seq_57330839_x1               ....................................agcgagUuauagaguuccua........................................................\t1',
 'seq_33749699_x172             ....................................agcgagguauagaguuccua........................................................\t0',
 'seq_49691106_x7               ....................................agcgagguauagaguuccuaU.......................................................\t1',
 'seq_38556180_x74              ....................................agcgagguauagaguuccuac.......................................................\t0',
 'seq_58209824_x1               ....................................agcgagguauagaAuuccuacg......................................................\t1',
 'seq_53344661_x3               ....................................agcgagguauagaguuccuacU......................................................\t1',
 'seq_56191458_x2               ....................................agcgagguauaUaguuccuacg......................................................\t1',
 'seq_57203802_x1               ....................................agcgagguauagaguuccuGcg......................................................\t1',
 'seq_55096862_x2               ....................................agcAagguauagaguuccuacg......................................................\t1',
 'seq_54714672_x2               ....................................agAgagguauagaguuccuacg......................................................\t1',
 'seq_58800100_x1               ....................................agcgagguUuagaguuccuacg......................................................\t1',
 'seq_56413554_x2               ....................................agcgaggAauagaguuccuacg......................................................\t1',
 'seq_58289175_x1               ....................................Cgcgagguauagaguuccuacg......................................................\t1',
 'seq_58875574_x1               ....................................agcgagguauagagCuccuacg......................................................\t1',
 'seq_15754907_x5701            ....................................agcgagguauagaguuccuacg......................................................\t0',
 'seq_59197827_x1               ....................................agcgagguauagaguuccCacg......................................................\t1',
 'seq_57400652_x1               ....................................agcgGgguauagaguuccuacg......................................................\t1',
 'seq_58532280_x1               ....................................agcgagguauGgaguuccuacg......................................................\t1',
 'seq_56512420_x2               ....................................agcgagguauagaguCccuacg......................................................\t1',
 'seq_58745861_x1               ....................................agcgagguauagaguuccuaAg......................................................\t1',
 'seq_54879742_x2               ....................................agcgagguauagaguuccAacg......................................................\t1',
 'seq_56841626_x1               ....................................agcgagguauagaguuccuaGg......................................................\t1',
 'seq_56759323_x1               ....................................agcgagguauagaguucUuacg......................................................\t1',
 'seq_59147500_x1               ....................................agcgagguauagaguuccuaUg......................................................\t1',
 'seq_56783871_x1               ....................................agcgagguauUgaguuccuacg......................................................\t1',
 'seq_58190575_x1               ....................................agcgaAguauagaguuccuacg......................................................\t1',
 'seq_54522464_x2               ....................................aNcgagguauagaguuccuacg......................................................\t1',
 'seq_57372786_x1               ....................................agcgagguaAagaguuccuacg......................................................\t1',
 'seq_57045844_x1               ....................................aCcgagguauagaguuccuacg......................................................\t1',
 'seq_52640539_x4               ....................................Ngcgagguauagaguuccuacg......................................................\t1',
 'seq_52212835_x4               ....................................agcgagguauagaguuccuacgA.....................................................\t1',
 'seq_58147603_x1               ....................................agcgagguauagaguuccuacguauauuAgc.............................................\t1',
 'seq_58748130_x1               ....................................agcgagguauagaguuccuacguauauuggcc............................................\t0',
 'seq_54131792_x3               .....................................gcgagguauagaguuccuac.......................................................\t0',
 'seq_49090552_x8               .....................................gcgagguauagaguuccuacg......................................................\t0',
 'seq_48308280_x10              ......................................cgagguauagaguuccuacg......................................................\t0',
 'seq_55616414_x2               .......................................gagguauagaguuccuacg......................................................\t0',
 'seq_56994709_x1               ........................................agguauagaguuccuacg......................................................\t0',
 'seq_47817486_x11              ....................................................................uAuaggaacuucauaccgugcucu....................\t1',
 'seq_51711999_x4               ....................................................................Cguaggaacuucauaccgugcucu....................\t1',
 'seq_48700839_x9               ....................................................................uUuaggaacuucauaccgugcucu....................\t1',
 'seq_50399823_x6               .....................................................................Uuaggaacuucauaccgugcuc.....................\t1',
 'seq_51366967_x5               .....................................................................Cuaggaacuucauaccgugcucu....................\t1',
 'seq_35818646_x120             .....................................................................Uuaggaacuucauaccgugcucu....................\t1',
 'seq_38857231_x70              .....................................................................Auaggaacuucauaccgugcucu....................\t1',
 'seq_51901487_x4               .....................................................................Uuaggaacuucauaccgugcucuu...................\t1',
 'seq_51457257_x5               ......................................................................uaggaacuucauaccgug........................\t0',
 'seq_48055070_x10              ......................................................................uaggaacuucauaccgugc.......................\t0',
 'seq_51400607_x5               ......................................................................uaggaacuucauaccgugA.......................\t1',
 'seq_58969819_x1               ......................................................................uagAaacuucauaccgugcu......................\t1',
 'seq_58636871_x1               ......................................................................uaggaacuucauaccgugcA......................\t1',
 'seq_57623281_x1               ......................................................................uaggaacuucauaUcgugcu......................\t1',
 'seq_24509940_x852             ......................................................................uaggaacuucauaccgugcu......................\t0',
 'seq_58857263_x1               ......................................................................uaggaacuucGuaccgugcu......................\t1',
 'seq_54950702_x2               ......................................................................Naggaacuucauaccgugcu......................\t1',
 'seq_55704496_x2               ......................................................................uaggaacuucauaccAugcuc.....................\t1',
 'seq_53896910_x3               ......................................................................uaggaacuucauaccgAgcuc.....................\t1',
 'seq_53918345_x3               ......................................................................uaggaacuucauaccgugcAc.....................\t1',
 'seq_59175718_x1               ......................................................................uaggaacuuUauaccgugcuc.....................\t1',
 'seq_54759416_x2               ......................................................................uaggaacAucauaccgugcuc.....................\t1',
 'seq_48789003_x9               ......................................................................Aaggaacuucauaccgugcuc.....................\t1',
 'seq_56451282_x2               ......................................................................Caggaacuucauaccgugcuc.....................\t1',
 'seq_52419583_x4               ......................................................................uaggaacuucauaccgugcuA.....................\t1',
 'seq_57917101_x1               ......................................................................uaggaacuucauGccgugcuc.....................\t1',
 'seq_57984408_x1               ......................................................................uaggaacuucGuaccgugcuc.....................\t1',
 'seq_56003586_x2               ......................................................................uaggaacuGcauaccgugcuc.....................\t1',
 'seq_53946689_x3               ......................................................................uaCgaacuucauaccgugcuc.....................\t1',
 'seq_56804538_x1               ......................................................................uaUgaacuucauaccgugcuc.....................\t1',
 'seq_49122824_x8               ......................................................................Naggaacuucauaccgugcuc.....................\t1',
 'seq_59239262_x1               ......................................................................uaggaaUuucauaccgugcuc.....................\t1',
 'seq_58971870_x1               ......................................................................uaggaGcuucauaccgugcuc.....................\t1',
 'seq_13047620_x12652           ......................................................................uaggaacuucauaccgugcuc.....................\t0',
 'seq_59077800_x1               ......................................................................Gaggaacuucauaccgugcuc.....................\t1',
 'seq_55831552_x2               ......................................................................uaggGacuucauaccgugcuc.....................\t1',
 'seq_52483439_x4               ......................................................................uaggaacuucauaccgugcuG.....................\t1',
 'seq_59046439_x1               ......................................................................uaggaacuucCuaccgugcuc.....................\t1',
 'seq_53743607_x3               ......................................................................uaggaaAuucauaccgugcuc.....................\t1',
 'seq_55447086_x2               ......................................................................uaggaacuucaAaccgugcuc.....................\t1',
 'seq_57057015_x1               ......................................................................uaggaacGucauaccgugcuc.....................\t1',
 'seq_54778788_x2               ......................................................................uaggaacuuAauaccgugcuc.....................\t1',
 'seq_59181242_x1               ......................................................................uaNgaacuucauaccgugcuc.....................\t1',
 'seq_58125091_x1               ......................................................................uaggaacuucauaccgugcCc.....................\t1',
 'seq_55668668_x2               ......................................................................uaggaCcuucauaccgugcuc.....................\t1',
 'seq_56237970_x2               ......................................................................uaggaacuAcauaccgugcuc.....................\t1',
 'seq_54708304_x2               ......................................................................uNggaacuucauaccgugcuc.....................\t1',
 'seq_58196813_x1               ......................................................................uaggaacuucaCaccgugcuc.....................\t1',
 'seq_57847140_x1               ......................................................................uaggaacCucauaccgugcuc.....................\t1',
 'seq_51592507_x4               ......................................................................uGggaacuucauaccgugcuc.....................\t1',
 'seq_55797606_x2               ......................................................................uaggaacuCcauaccgugcuc.....................\t1',
 'seq_46499484_x15              ......................................................................uaggaacuucauaccgugcuU.....................\t1',
 'seq_53358080_x3               ......................................................................uCggaacuucauaccgugcuc.....................\t1',
 'seq_58133312_x1               ......................................................................uaggaacuucauaccgugAuc.....................\t1',
 'seq_41192242_x45              ......................................................................Gaggaacuucauaccgugcucu....................\t1',
 'seq_47826572_x11              ......................................................................uaggaacuucauaccgugGucu....................\t1',
 'seq_35849307_x119             ......................................................................uNggaacuucauaccgugcucu....................\t1',
 'seq_37359601_x92              ......................................................................uaggaacuucGuaccgugcucu....................\t1',
 'seq_39590659_x61              ......................................................................uaggaacuucauaccAugcucu....................\t1',
 'seq_43462658_x29              ......................................................................uagUaacuucauaccgugcucu....................\t1',
 'seq_44482903_x23              ......................................................................uaggaaUuucauaccgugcucu....................\t1',
 'seq_28344717_x430             ......................................................................uaggaacuucauaccgugcucC....................\t1',
 'seq_38670609_x72              ......................................................................uaggaCcuucauaccgugcucu....................\t1',
 'seq_50164641_x6               ......................................................................uaggaacuucauaGcgugcucu....................\t1',
 'seq_48244420_x10              ......................................................................uaggaacuucauaccguCcucu....................\t1',
 'seq_36729383_x102             ......................................................................uaggaacuucauaccgAgcucu....................\t1',
 'seq_40234637_x54              ......................................................................uaggaacuucauaccgugcAcu....................\t1',
 'seq_36089241_x114             ......................................................................uaggaacuucauacAgugcucu....................\t1',
 'seq_46009686_x17              ......................................................................uUggaacuucauaccgugcucu....................\t1',
 'seq_48898776_x9               ......................................................................uaggaacuucCuaccgugcucu....................\t1',
 'seq_35277570_x132             ......................................................................uaggaGcuucauaccgugcucu....................\t1',
 'seq_51738887_x4               ......................................................................uaggaacuucaGaccgugcucu....................\t1',
 'seq_55562394_x2               ......................................................................uaggCacuucauaccgugcucu....................\t1',
 'seq_34844845_x142             ......................................................................uaggaacuCcauaccgugcucu....................\t1',
 'seq_56144844_x2               ......................................................................uaggaacuucauacGgugcucu....................\t1',
 'seq_33723211_x172             ......................................................................uaggaacuucauaccgugcucA....................\t1',
 'seq_40940993_x48              ......................................................................uaUgaacuucauaccgugcucu....................\t1',
 'seq_41254477_x45              ......................................................................uaggaacuucauaccgugAucu....................\t1',
 'seq_42789609_x33              ......................................................................uagNaacuucauaccgugcucu....................\t1',

In [134]:
entries = []
temp = []

for item in read_data:
    if item.startswith('>'):
        if temp:
            entries.append(temp)
        temp = [item]
    else:
        if not item == '':
            temp.append(item)

if temp:
    entries.append(temp)

In [135]:
entries[1]

['>QFTL02000019.1_8885',
 'score total\t\t           5.5',
 'score for star read(s)\t          -1.3',
 'score for read counts\t 0',
 'score for mfe\t\t           2.2',
 'score for randfold\t           1.6',
 'score for cons. seed\t             3',
 'miRNA with same seed\t  bmo-mir-2770',
 'total read count\t       1271611',
 'mature read count\t       1271428',
 'loop read count\t\t 0',
 'star read count\t\t           183',
 'exp                           fffffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSlllllllllllMMMMMMMMMMMMMMMMMMMMffffffffffffffffff',
 'obs                           fffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSlllllllllllMMMMMMMMMMMMMMMMMMMMffffffffffffffffff',
 'pri_seq                       cguguucaacaucgguggagagacuggcauccccuguccaucauuuggcuugacugcugcuguccacgcaucagucuugucgaaugguggguggguggugccuuguac',
 'pri_struct                    .((.(((..((....))..))))).((((((.((..(((((((((((((..(((((.(((.......))).)))))..)))))))))))))..)).))))))......\t#MM',
 'seq_57094601_x1               ...guucaacaucgguggagagacuggcauccc...........................................................................\t0',
 'seq_48489465_x9               .....ucaacaucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_52616015_x4               ......caacaucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_57225726_x1               .......aacaucgguggagagacuggcaucc............................................................................\t0',
 'seq_54802172_x2               .........caucgguggagagacuggcauccc...........................................................................\t0',
 'seq_56313144_x2               .........caucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_50548785_x6               ............cgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_58899102_x1               ..............guggagagacuggcauccccugu.......................................................................\t0',
 'seq_45135843_x20              .................gagagacuggcauccccugu.......................................................................\t0',
 'seq_54438302_x2               .................gagagacuggcauccccuguA......................................................................\t1',
 'seq_52263847_x4               ..................agagacuggcauccccugu.......................................................................\t0',
 'seq_47656523_x11              ...................gagacuggcauccccugu.......................................................................\t0',
 'seq_54377106_x2               ...................gagacuggcauccccuguA......................................................................\t1',
 'seq_59177255_x1               ....................................uccaucauuuggcuugacugcu..................................................\t0',
 'seq_43025473_x32              .....................................ccaucauuuggcuugacugc...................................................\t0',
 'seq_45312283_x20              .....................................ccaucauuuggcuugacugcu..................................................\t0',
 'seq_51711715_x4               .....................................ccaucauuuggcuugacugcA..................................................\t1',
 'seq_59179536_x1               .....................................ccaucauuuggUuugacugcug.................................................\t1',
 'seq_53157188_x3               .....................................ccaucauuuggcuugacugcuU.................................................\t1',
 'seq_35834726_x120             .....................................ccaucauuuggcuugacugcug.................................................\t0',
 'seq_58234786_x1               .....................................ccaucauuuggcuugacugcugU................................................\t1',
 'seq_56927731_x1               .....................................ccaucauuuggcuugacugcugUu...............................................\t1',
 'seq_58713992_x1               .....................................ccaucauuuggcuugacugcugcu...............................................\t0',
 'seq_55188944_x2               ............................................................uguccacgcaucagucuugucgaaug......................\t0',
 'seq_54225866_x3               ...................................................................gcGucagucuugucgaauggugggu................\t1',
 'seq_53626049_x3               ....................................................................cUucagucuugucgaauggug...................\t1',
 'seq_58624432_x1               ....................................................................Aaucagucuugucgaauggug...................\t1',
 'seq_40926353_x48              ....................................................................cUucagucuugucgaauggugg..................\t1',
 'seq_49737131_x7               ....................................................................Aaucagucuugucgaauggugg..................\t1',
 'seq_54265265_x3               ....................................................................caucagucuugucgaauggugg..................\t0',
 'seq_57186402_x1               ....................................................................cGucagucuugucgaauggugg..................\t1',
 'seq_55509446_x2               ....................................................................cUucagucuugucgaaugguggg.................\t1',
 'seq_47849056_x11              ....................................................................Aaucagucuugucgaauggugggu................\t1',
 'seq_53856335_x3               ....................................................................Gaucagucuugucgaauggugggu................\t1',
 'seq_49176792_x8               ....................................................................Uaucagucuugucgaauggugggu................\t1',
 'seq_39738024_x60              ....................................................................cUucagucuugucgaauggugggu................\t1',
 'seq_55898440_x2               .....................................................................aucagucuugucgaauggu....................\t0',
 'seq_53223896_x3               .....................................................................aucagucuugucgaauggug...................\t0',
 'seq_49982698_x7               .....................................................................Uucagucuugucgaauggug...................\t1',
 'seq_42874221_x33              .....................................................................aucagucuugucgaauggugg..................\t0',
 'seq_57737608_x1               .....................................................................aucGgucuugucgaauggugg..................\t1',
 'seq_56854243_x1               .....................................................................aucagucuugucgaaugguCg..................\t1',
 'seq_50963932_x5               .....................................................................Cucagucuugucgaauggugg..................\t1',
 'seq_58277451_x1               .....................................................................Gucagucuugucgaauggugg..................\t1',
 'seq_36627260_x104             .....................................................................Uucagucuugucgaauggugg..................\t1',
 'seq_58738027_x1               .....................................................................aucagucuugucgaaugguggg.................\t0',
 'seq_54675740_x2               .....................................................................Uucagucuugucgaaugguggg.................\t1',
 'seq_57295766_x1               .....................................................................aucagCcuugucgaauggugggu................\t1',
 'seq_57225529_x1               .....................................................................Cucagucuugucgaauggugggu................\t1',
 'seq_57641972_x1               .....................................................................auAagucuugucgaauggugggu................\t1',
 'seq_41133646_x46              .....................................................................aucagucuugucgaauggugggu................\t0',
 'seq_37421905_x91              .....................................................................Uucagucuugucgaauggugggu................\t1',
 'seq_56987260_x1               .....................................................................aucagucuugucgaaugguggguU...............\t1',
 'seq_57900416_x1               ......................................................................uNagucuugucgaauggu....................\t1',
 'seq_58236191_x1               ......................................................................ucagucGugucgaauggu....................\t1',
 'seq_57605579_x1               ......................................................................ucagGcuugucgaauggu....................\t1',
 'seq_58569446_x1               ......................................................................ucagucCugucgaauggu....................\t1',
 'seq_25036800_x773             ......................................................................ucagucuugucgaauggu....................\t0',
 'seq_54830620_x2               ......................................................................ucagucuugucgaauUgug...................\t1',
 'seq_48058620_x10              ......................................................................ucagAcuugucgaauggug...................\t1',
 'seq_51744747_x4               ......................................................................ucagucAugucgaauggug...................\t1',
 'seq_57865318_x1               ......................................................................ucagucuugucgaUuggug...................\t1',
 'seq_57945078_x1               ......................................................................ucUgucuugucgaauggug...................\t1',
 'seq_50746777_x5               ......................................................................ucagucuugucgaauCgug...................\t1',
 'seq_56266140_x2               ......................................................................ucCgucuugucgaauggug...................\t1',
 'seq_50724812_x5               ......................................................................ucagGcuugucgaauggug...................\t1',
 'seq_50595663_x6               ......................................................................ucagCcuugucgaauggug...................\t1',
 'seq_58908750_x1               ......................................................................ucagucuugucgUauggug...................\t1',
 'seq_49860926_x7               ......................................................................ucagucuugAcgaauggug...................\t1',
 'seq_39839587_x58              ......................................................................Ncagucuugucgaauggug...................\t1',
 'seq_51171772_x5               ......................................................................ucagucuugucgaaCggug...................\t1',
 'seq_50835107_x5               ......................................................................ucagucCugucgaauggug...................\t1',
 'seq_57201563_x1               ......................................................................ucagucuugucgaaugCug...................\t1',
 'seq_46610514_x15              ......................................................................uAagucuugucgaauggug...................\t1',
 'seq_48380530_x10              ......................................................................ucagucuugucgaauggCg...................\t1',
 'seq_48813906_x9               ......................................................................ucagucuugucgaaugguC...................\t1',
 'seq_45960284_x17              ......................................................................ucagucuugucgaaAggug...................\t1',
 'seq_48265280_x10              ......................................................................ucagucuugucgGauggug...................\t1',
 'seq_50366829_x6               ......................................................................ucagucGugucgaauggug...................\t1',
 'seq_51288537_x5               ......................................................................ucagucuugucUaauggug...................\t1',
 'seq_30440599_x303             ......................................................................ucagucuugucgaaugguA...................\t1',
 'seq_48228380_x10              ......................................................................Ccagucuugucgaauggug...................\t1',
 'seq_53641007_x3               ......................................................................ucagucuugucgaauggGg...................\t1',
 'seq_54658980_x2               ......................................................................ucagucuugGcgaauggug...................\t1',
 'seq_49093408_x8               ......................................................................ucagucuugCcgaauggug...................\t1',
 'seq_48000691_x11              ......................................................................ucagucuCgucgaauggug...................\t1',
 'seq_56345518_x2               ......................................................................ucaAucuugucgaauggug...................\t1',
 'seq_56020610_x2               ......................................................................ucagucuugucgaCuggug...................\t1',
 'seq_52600063_x4               ......................................................................ucagucuugucAaauggug...................\t1',
 'seq_48312680_x10              ......................................................................ucagucuuguAgaauggug...................\t1',
 'seq_50616873_x6               ......................................................................ucagucuugucgaauggAg...................\t1',
 'seq_38308044_x77              ......................................................................ucagucuugucgaaugguU...................\t1',
 'seq_51428677_x5               ......................................................................ucaguGuugucgaauggug...................\t1',
 'seq_54166886_x3               ......................................................................ucagucuuguGgaauggug...................\t1',
 'seq_56877037_x1               ......................................................................uGagucuugucgaauggug...................\t1',
 'seq_49673214_x7               ......................................................................ucagucuAgucgaauggug...................\t1',
 'seq_53930723_x3               ......................................................................uUagucuugucgaauggug...................\t1',
 'seq_52195467_x4               ......................................................................ucagucuGgucgaauggug...................\t1',
 'seq_47169841_x13              ......................................................................ucGgucuugucgaauggug...................\t1',
 'seq_9040075_x61670            ......................................................................ucagucuugucgaauggug...................\t0',
 'seq_54780514_x2               ......................................................................ucaNucuugucgaauggug...................\t1',
 'seq_50936557_x5               ......................................................................Gcagucuugucgaauggug...................\t1',
 'seq_51728895_x4               ......................................................................ucagucuugucCaauggug...................\t1',
 'seq_50507643_x6               ......................................................................ucaguAuugucgaauggug...................\t1',
 'seq_53725607_x3               ......................................................................ucagucuuAucgaauggug...................\t1',
 'seq_49065512_x8               ......................................................................ucagucuugucgaGuggug...................\t1',
 'seq_58676882_x1               ......................................................................ucagucuugucgaaugAug...................\t1',
 'seq_52956260_x3               ......................................................................ucaguUuugucgaauggug...................\t1',
 'seq_57260654_x1               ......................................................................ucagucuuCucgaauggug...................\t1',
 'seq_50936627_x5               ......................................................................ucagucuugucgaaugUug...................\t1',
 'seq_46497399_x15              ......................................................................uNagucuugucgaauggug...................\t1',
 'seq_57930035_x1               ......................................................................ucagucuuguUgaauggug...................\t1',
 'seq_47495254_x12              ......................................................................ucagucuuUucgaauggug...................\t1',
 'seq_47389390_x12              ......................................................................Acagucuugucgaauggug...................\t1',
 'seq_44669236_x22              ......................................................................ucaUucuugucgaauggugg..................\t1',
 'seq_40009151_x57              ......................................................................ucagGcuugucgaauggugg..................\t1',
 'seq_49268832_x8               ......................................................................ucaAucuugucgaauggugg..................\t1',
 'seq_39328329_x64              ......................................................................ucagucuugucAaauggugg..................\t1',
 'seq_21435120_x1556            ......................................................................ucagucuugucgaauggugU..................\t1',
 'seq_44378543_x24              ......................................................................ucagucuugucgaCuggugg..................\t1',
 'seq_38542046_x74              ......................................................................ucagucuCgucgaauggugg..................\t1',
 'seq_27840480_x468             ......................................................................Ncagucuugucgaauggugg..................\t1',
 'seq_58957851_x1               ......................................................................ucagNcuugucgaauggugg..................\t1',
 'seq_39113273_x67              ......................................................................ucagucuugucgaaugUugg..................\t1',
 'seq_40524357_x51              ......................................................................ucagucAugucgaauggugg..................\t1',
 'seq_41594896_x42              ......................................................................uUagucuugucgaauggugg..................\t1',
 'seq_29680695_x342             ......................................................................ucagucuugucgaauggugA..................\t1',
 'seq_48665343_x9               ......................................................................ucagucuuguGgaauggugg..................\t1',
 'seq_38689761_x72              ......................................................................ucagucuugucgaaugguUg..................\t1',
 'seq_36101097_x114             ......................................................................ucagucuugucgaauUgugg..................\t1',

In [136]:
alignments = [[item.strip() for item in entry if (item.startswith('seq_') or item.startswith('obs') or item.startswith('exp'))] for entry in entries]

In [137]:
alignments[1]

['exp                           fffffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSlllllllllllMMMMMMMMMMMMMMMMMMMMffffffffffffffffff',
 'obs                           fffffffffffffffffffffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSlllllllllllMMMMMMMMMMMMMMMMMMMMffffffffffffffffff',
 'seq_57094601_x1               ...guucaacaucgguggagagacuggcauccc...........................................................................\t0',
 'seq_48489465_x9               .....ucaacaucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_52616015_x4               ......caacaucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_57225726_x1               .......aacaucgguggagagacuggcaucc............................................................................\t0',
 'seq_54802172_x2               .........caucgguggagagacuggcauccc...........................................................................\t0',
 'seq_56313144_x2               .........caucgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_50548785_x6               ............cgguggagagacuggcauccccugu.......................................................................\t0',
 'seq_58899102_x1               ..............guggagagacuggcauccccugu.......................................................................\t0',
 'seq_45135843_x20              .................gagagacuggcauccccugu.......................................................................\t0',
 'seq_54438302_x2               .................gagagacuggcauccccuguA......................................................................\t1',
 'seq_52263847_x4               ..................agagacuggcauccccugu.......................................................................\t0',
 'seq_47656523_x11              ...................gagacuggcauccccugu.......................................................................\t0',
 'seq_54377106_x2               ...................gagacuggcauccccuguA......................................................................\t1',
 'seq_59177255_x1               ....................................uccaucauuuggcuugacugcu..................................................\t0',
 'seq_43025473_x32              .....................................ccaucauuuggcuugacugc...................................................\t0',
 'seq_45312283_x20              .....................................ccaucauuuggcuugacugcu..................................................\t0',
 'seq_51711715_x4               .....................................ccaucauuuggcuugacugcA..................................................\t1',
 'seq_59179536_x1               .....................................ccaucauuuggUuugacugcug.................................................\t1',
 'seq_53157188_x3               .....................................ccaucauuuggcuugacugcuU.................................................\t1',
 'seq_35834726_x120             .....................................ccaucauuuggcuugacugcug.................................................\t0',
 'seq_58234786_x1               .....................................ccaucauuuggcuugacugcugU................................................\t1',
 'seq_56927731_x1               .....................................ccaucauuuggcuugacugcugUu...............................................\t1',
 'seq_58713992_x1               .....................................ccaucauuuggcuugacugcugcu...............................................\t0',
 'seq_55188944_x2               ............................................................uguccacgcaucagucuugucgaaug......................\t0',
 'seq_54225866_x3               ...................................................................gcGucagucuugucgaauggugggu................\t1',
 'seq_53626049_x3               ....................................................................cUucagucuugucgaauggug...................\t1',
 'seq_58624432_x1               ....................................................................Aaucagucuugucgaauggug...................\t1',
 'seq_40926353_x48              ....................................................................cUucagucuugucgaauggugg..................\t1',
 'seq_49737131_x7               ....................................................................Aaucagucuugucgaauggugg..................\t1',
 'seq_54265265_x3               ....................................................................caucagucuugucgaauggugg..................\t0',
 'seq_57186402_x1               ....................................................................cGucagucuugucgaauggugg..................\t1',
 'seq_55509446_x2               ....................................................................cUucagucuugucgaaugguggg.................\t1',
 'seq_47849056_x11              ....................................................................Aaucagucuugucgaauggugggu................\t1',
 'seq_53856335_x3               ....................................................................Gaucagucuugucgaauggugggu................\t1',
 'seq_49176792_x8               ....................................................................Uaucagucuugucgaauggugggu................\t1',
 'seq_39738024_x60              ....................................................................cUucagucuugucgaauggugggu................\t1',
 'seq_55898440_x2               .....................................................................aucagucuugucgaauggu....................\t0',
 'seq_53223896_x3               .....................................................................aucagucuugucgaauggug...................\t0',
 'seq_49982698_x7               .....................................................................Uucagucuugucgaauggug...................\t1',
 'seq_42874221_x33              .....................................................................aucagucuugucgaauggugg..................\t0',
 'seq_57737608_x1               .....................................................................aucGgucuugucgaauggugg..................\t1',
 'seq_56854243_x1               .....................................................................aucagucuugucgaaugguCg..................\t1',
 'seq_50963932_x5               .....................................................................Cucagucuugucgaauggugg..................\t1',
 'seq_58277451_x1               .....................................................................Gucagucuugucgaauggugg..................\t1',
 'seq_36627260_x104             .....................................................................Uucagucuugucgaauggugg..................\t1',
 'seq_58738027_x1               .....................................................................aucagucuugucgaaugguggg.................\t0',
 'seq_54675740_x2               .....................................................................Uucagucuugucgaaugguggg.................\t1',
 'seq_57295766_x1               .....................................................................aucagCcuugucgaauggugggu................\t1',
 'seq_57225529_x1               .....................................................................Cucagucuugucgaauggugggu................\t1',
 'seq_57641972_x1               .....................................................................auAagucuugucgaauggugggu................\t1',
 'seq_41133646_x46              .....................................................................aucagucuugucgaauggugggu................\t0',
 'seq_37421905_x91              .....................................................................Uucagucuugucgaauggugggu................\t1',
 'seq_56987260_x1               .....................................................................aucagucuugucgaaugguggguU...............\t1',
 'seq_57900416_x1               ......................................................................uNagucuugucgaauggu....................\t1',
 'seq_58236191_x1               ......................................................................ucagucGugucgaauggu....................\t1',
 'seq_57605579_x1               ......................................................................ucagGcuugucgaauggu....................\t1',
 'seq_58569446_x1               ......................................................................ucagucCugucgaauggu....................\t1',
 'seq_25036800_x773             ......................................................................ucagucuugucgaauggu....................\t0',
 'seq_54830620_x2               ......................................................................ucagucuugucgaauUgug...................\t1',
 'seq_48058620_x10              ......................................................................ucagAcuugucgaauggug...................\t1',
 'seq_51744747_x4               ......................................................................ucagucAugucgaauggug...................\t1',
 'seq_57865318_x1               ......................................................................ucagucuugucgaUuggug...................\t1',
 'seq_57945078_x1               ......................................................................ucUgucuugucgaauggug...................\t1',
 'seq_50746777_x5               ......................................................................ucagucuugucgaauCgug...................\t1',
 'seq_56266140_x2               ......................................................................ucCgucuugucgaauggug...................\t1',
 'seq_50724812_x5               ......................................................................ucagGcuugucgaauggug...................\t1',
 'seq_50595663_x6               ......................................................................ucagCcuugucgaauggug...................\t1',
 'seq_58908750_x1               ......................................................................ucagucuugucgUauggug...................\t1',
 'seq_49860926_x7               ......................................................................ucagucuugAcgaauggug...................\t1',
 'seq_39839587_x58              ......................................................................Ncagucuugucgaauggug...................\t1',
 'seq_51171772_x5               ......................................................................ucagucuugucgaaCggug...................\t1',
 'seq_50835107_x5               ......................................................................ucagucCugucgaauggug...................\t1',
 'seq_57201563_x1               ......................................................................ucagucuugucgaaugCug...................\t1',
 'seq_46610514_x15              ......................................................................uAagucuugucgaauggug...................\t1',
 'seq_48380530_x10              ......................................................................ucagucuugucgaauggCg...................\t1',
 'seq_48813906_x9               ......................................................................ucagucuugucgaaugguC...................\t1',
 'seq_45960284_x17              ......................................................................ucagucuugucgaaAggug...................\t1',
 'seq_48265280_x10              ......................................................................ucagucuugucgGauggug...................\t1',
 'seq_50366829_x6               ......................................................................ucagucGugucgaauggug...................\t1',
 'seq_51288537_x5               ......................................................................ucagucuugucUaauggug...................\t1',
 'seq_30440599_x303             ......................................................................ucagucuugucgaaugguA...................\t1',
 'seq_48228380_x10              ......................................................................Ccagucuugucgaauggug...................\t1',
 'seq_53641007_x3               ......................................................................ucagucuugucgaauggGg...................\t1',
 'seq_54658980_x2               ......................................................................ucagucuugGcgaauggug...................\t1',
 'seq_49093408_x8               ......................................................................ucagucuugCcgaauggug...................\t1',
 'seq_48000691_x11              ......................................................................ucagucuCgucgaauggug...................\t1',
 'seq_56345518_x2               ......................................................................ucaAucuugucgaauggug...................\t1',
 'seq_56020610_x2               ......................................................................ucagucuugucgaCuggug...................\t1',
 'seq_52600063_x4               ......................................................................ucagucuugucAaauggug...................\t1',
 'seq_48312680_x10              ......................................................................ucagucuuguAgaauggug...................\t1',
 'seq_50616873_x6               ......................................................................ucagucuugucgaauggAg...................\t1',
 'seq_38308044_x77              ......................................................................ucagucuugucgaaugguU...................\t1',
 'seq_51428677_x5               ......................................................................ucaguGuugucgaauggug...................\t1',
 'seq_54166886_x3               ......................................................................ucagucuuguGgaauggug...................\t1',
 'seq_56877037_x1               ......................................................................uGagucuugucgaauggug...................\t1',
 'seq_49673214_x7               ......................................................................ucagucuAgucgaauggug...................\t1',
 'seq_53930723_x3               ......................................................................uUagucuugucgaauggug...................\t1',
 'seq_52195467_x4               ......................................................................ucagucuGgucgaauggug...................\t1',
 'seq_47169841_x13              ......................................................................ucGgucuugucgaauggug...................\t1',
 'seq_9040075_x61670            ......................................................................ucagucuugucgaauggug...................\t0',
 'seq_54780514_x2               ......................................................................ucaNucuugucgaauggug...................\t1',
 'seq_50936557_x5               ......................................................................Gcagucuugucgaauggug...................\t1',
 'seq_51728895_x4               ......................................................................ucagucuugucCaauggug...................\t1',
 'seq_50507643_x6               ......................................................................ucaguAuugucgaauggug...................\t1',
 'seq_53725607_x3               ......................................................................ucagucuuAucgaauggug...................\t1',
 'seq_49065512_x8               ......................................................................ucagucuugucgaGuggug...................\t1',
 'seq_58676882_x1               ......................................................................ucagucuugucgaaugAug...................\t1',
 'seq_52956260_x3               ......................................................................ucaguUuugucgaauggug...................\t1',
 'seq_57260654_x1               ......................................................................ucagucuuCucgaauggug...................\t1',
 'seq_50936627_x5               ......................................................................ucagucuugucgaaugUug...................\t1',
 'seq_46497399_x15              ......................................................................uNagucuugucgaauggug...................\t1',
 'seq_57930035_x1               ......................................................................ucagucuuguUgaauggug...................\t1',
 'seq_47495254_x12              ......................................................................ucagucuuUucgaauggug...................\t1',
 'seq_47389390_x12              ......................................................................Acagucuugucgaauggug...................\t1',
 'seq_44669236_x22              ......................................................................ucaUucuugucgaauggugg..................\t1',
 'seq_40009151_x57              ......................................................................ucagGcuugucgaauggugg..................\t1',
 'seq_49268832_x8               ......................................................................ucaAucuugucgaauggugg..................\t1',
 'seq_39328329_x64              ......................................................................ucagucuugucAaauggugg..................\t1',
 'seq_21435120_x1556            ......................................................................ucagucuugucgaauggugU..................\t1',
 'seq_44378543_x24              ......................................................................ucagucuugucgaCuggugg..................\t1',
 'seq_38542046_x74              ......................................................................ucagucuCgucgaauggugg..................\t1',
 'seq_27840480_x468             ......................................................................Ncagucuugucgaauggugg..................\t1',
 'seq_58957851_x1               ......................................................................ucagNcuugucgaauggugg..................\t1',
 'seq_39113273_x67              ......................................................................ucagucuugucgaaugUugg..................\t1',
 'seq_40524357_x51              ......................................................................ucagucAugucgaauggugg..................\t1',
 'seq_41594896_x42              ......................................................................uUagucuugucgaauggugg..................\t1',
 'seq_29680695_x342             ......................................................................ucagucuugucgaauggugA..................\t1',
 'seq_48665343_x9               ......................................................................ucagucuuguGgaauggugg..................\t1',
 'seq_38689761_x72              ......................................................................ucagucuugucgaaugguUg..................\t1',
 'seq_36101097_x114             ......................................................................ucagucuugucgaauUgugg..................\t1',
 'seq_39592428_x61              ......................................................................ucagucuugucgGauggugg..................\t1',
 'seq_38206391_x79              ......................................................................ucagucuugucgaauggCgg..................\t1',
 'seq_39126673_x67              ......................................................................ucagucuugCcgaauggugg..................\t1',
 'seq_44256263_x24              ......................................................................ucagucuuAucgaauggugg..................\t1',
 'seq_34973584_x139             ......................................................................ucagucGugucgaauggugg..................\t1',

In [ ]:
# cell 7 – rewritten
import re
import pandas as pd

def parse_seq_entry(seq_line):
    s = seq_line.strip()
    # drop trailing tab/flag like "\t0" if present
    s = re.sub(r'\t.*$', '', s).strip()
    # remove surrounding quotes if any
    s = s.strip('\'"')
    m = re.match(r'^(seq_[0-9]+)_x(\d+)\s+(.*)$', s)
    consensus = re.match(r'(exp|obs)\s(.+)$', s)

    if consensus:
        return 'consensus', 1, consensus.group(2).strip()
    if m:
        return m.group(1), int(m.group(2)), m.group(3).strip()
    # fallback: first token contains id_count, rest is alignment
    parts = s.split(None, 1)
    if parts:
        m2 = re.match(r'^(seq_[0-9]+)_x(\d+)$', parts[0])
        if m2:
            alignment = parts[1].strip() if len(parts) > 1 else ''
            return m2.group(1), int(m2.group(2)), alignment
    return None, None, s

# build dataframes, dropping the 'exp' consensus only when an 'obs' is present
dfs = []
for idx, entry in enumerate(alignments):
    has_obs = any(line.strip().startswith('obs') for line in entry)
    rows = []
    for line in entry:
        if has_obs and line.strip().startswith('exp'):
            # skip the exp consensus if an obs consensus exists in this entry for more accurate downstream analysis
            continue
        name, count, aln = parse_seq_entry(line)
        if name is not None:
            rows.append((name, count, aln))

    df = pd.DataFrame(rows, columns=['sequence_name', 'sequence_count', 'alignment'])
    dfs.append(df)

# example
dfs[1].head()

,sequence_name,sequence_count,alignment
0,consensus,1,fffffffffffffffffffffffffffffffffffffSSSSSSSSS...
1,seq_57094601,1,...guucaacaucgguggagagacuggcauccc................
2,seq_48489465,9,.....ucaacaucgguggagagacuggcauccccugu............
3,seq_52616015,4,......caacaucgguggagagacuggcauccccugu............
4,seq_57225726,1,.......aacaucgguggagagacuggcaucc.................

In [109]:
combined = pd.concat(
    [df.assign(entry_index=i) for i, df in enumerate(dfs)],
    ignore_index=True
)
combined.head()

,sequence_name,sequence_count,alignment,entry_index
0,consensus,1,ffffffffffffffffffffffffffffffffffffSSSSSSSSSS...,0
1,seq_57026257,1,..................caccuggugauugccacu.............,0
2,seq_55564128,2,..........................gauugccacuagcgagguau...,0
3,seq_53349098,3,.................................Ucuagcgagguau...,0
4,seq_57407504,1,...................................Cagcgagguau...,0

In [110]:
test_case = combined[combined['entry_index'] == 2]
test_case

,sequence_name,sequence_count,alignment,entry_index
577,consensus,1,ffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSSlllll...,2
578,seq_58643452,1,.........uauuugaacuguagugccgc....................,2
579,seq_50138007,6,...........uuugaacuguagugccgcuccg................,2
580,seq_49764620,7,..........................cgcuccgaugauuucaccag...,2
581,seq_51972427,4,.................................................,2
...,...,...,...,...
977,seq_55345684,2,.................................................,2
978,seq_55503424,2,.................................................,2
979,seq_53706002,3,.................................................,2
980,seq_58007736,1,.................................................,2
981,seq_57658083,1,.................................................,2

Extract 5' start coordinate: For each read alignment string, find the index of the first nucleotide character (A/C/G/T/U/N, case-insensitive). Use the read's _x<count> as weight. Optionally convert index → genomic/pre-miRNA coordinate if you have a reference offset.

Dominant-start proportion:

Compute counts p_i for each 5' start position i (weighted by _x<count>).
Metric: dominant_prop = max(p_i) / sum(p_i).
Interpretation: high (e.g., >0.7–0.8) → strong 5' homogeneity.
Normalized Shannon entropy:

H = -sum_i p_i * log(p_i). Normalized H' = H / log(k) where k = number of observed start positions.
Low H' (close to 0) → homogeneous; high (close to 1) → heterogeneous. Thresholds: H' < 0.25 strong, 0.25–0.5 moderate.
Gini coefficient / inequality:

Compute Gini on the start counts distribution. Higher Gini → more concentrated (homogeneous). Use as alternative to entropy.
n90 (compactness):

Compute the minimum number of distinct start positions that together account for 90% of reads. n90 ≤ 2 → homogeneous.
Tolerance-window aggregation (handles micro-heterogeneity ±1 nt):

Merge counts across windows of ±1 (or ±2) nt and recompute dominant_prop / H'. Useful because enzymatic processing can produce 1-nt shifts.
Peak detection / KDE:

Smooth start-position counts with a small kernel, identify peak(s), compute peak height vs background (peak / median or peak / mean). High peak/background indicates homogeneity.
Statistical test vs null:

Null: uniform or background distribution from reads mapped elsewhere. Use chi-square or permutation (shuffle read starts among positions) to obtain p-value that observed concentration is non-random.
Sequence-consistency at 5' nucleotide:

For reads starting at the dominant position, compute fraction with identical first nucleotide and identical first 2–3 nt. True miRNAs often show consistent 5' bases.
Composite homogeneity score:

Combine metrics, e.g.: score = 0.5dominant_prop + 0.3(1 - H') + 0.2*(1 - n90/10) (normalize appropriately). Tune weights on labeled data.
Extraction pseudocode (5' pos + counts):

For each line in alignments:
parse count from name _x\d+
extract aln = alignment string (strip trailing \t flags)
start_idx = index of first nucleotide character in aln (0-based)
increment position counter: counts[start_idx] += count
Suggested thresholds (starting points):

dominant_prop ≥ 0.7 and normalized entropy ≤ 0.3 and n90 ≤ 2 → call highly_homogeneous.
dominant_prop 0.5–0.7 → moderately_homogeneous.
else → heterogeneous.
Notes / caveats:

Decide coordinate frame (alignment index vs genome coordinate). If alignments include flanking dots, using first-nucleotide index is sufficient for comparing within an entry.
Use _x<count> weights to avoid treating each distinct sequence string equally when counts vary widely.
Allow ±1 nt tolerance for micro-heterogeneity — recompute metrics with and without tolerance to report both strict and tolerant homogeneity.
Next step: implement one or more of these metrics in the notebook and add summary columns (dominant_prop, entropy, n90, composite_score) to your combined DataFrame. Want me to implement the strict + ±1-nt tolerant versions as notebook cells and show the results?

GPT-5 mini • 1x

In [111]:
test_alignments, test_counts = test_case['alignment'].to_numpy(), test_case['sequence_count'].to_numpy()
test_alignments

array(['ffffffffffffffffffSSSSSSSSSSSSSSSSSSSSSSSlllllllllllllllllllllllllllllMMMMMMMMMMMMMMMMMMMMMMMffffffffffffffff',
       '.........uauuugaacuguagugccgc................................................................................',
       '...........uuugaacuguagugccgcuccg............................................................................',
       '..........................cgcuccgaugauuucaccagaaga...........................................................',
       '..................................................................gggaaggcaagaugucggcauagc...................',
       '...................................................................ggaaggcaagaugucggcauagc...................',
       '....................................................................gaaggcaagaugucggcaua.....................',
       '....................................................................gaaggcaagaugucggcauag....................',
       '....................................................................gaaggcaagaugucggcauagc...................',
       '....................................................................gaaggcaagaugucggcauagcu..................',
       '....................................................................gCaggcaagaugucggcauagcuga................',
       '.....................................................................aaggcaagaugucggcaua.....................',
       '.....................................................................aaggcaagaugucggcauag....................',
       '.....................................................................aaggcaagaugucggcGuag....................',
       '.....................................................................Uaggcaagaugucggcauag....................',
       '.....................................................................aaggcaagauguAggcauag....................',
       '.....................................................................Caggcaagaugucggcauagc...................',
       '.....................................................................aaggcaagaugucggcauagc...................',
       '.....................................................................Uaggcaagaugucggcauagc...................',
       '.....................................................................Gaggcaagaugucggcauagc...................',
       '.....................................................................aaggcaagaugucggcauagA...................',
       '.....................................................................aaggcGagaugucggcauagc...................',
       '.....................................................................Naggcaagaugucggcauagc...................',
       '.....................................................................aGggcaagaugucggcauagc...................',
       '.....................................................................aaggcaagaugucggcauagU...................',
       '.....................................................................aaggAaagaugucggcauagc...................',
       '.....................................................................aaggcaagaugucggcauagAu..................',
       '.....................................................................aaggcaagauUucggcauagcu..................',
       '.....................................................................aaggcaagaugucggcauagcC..................',
       '.....................................................................aaggcaagaugucggcauagcu..................',
       '.....................................................................aaggcaagauAucggcauagcu..................',
       '.....................................................................Uaggcaagaugucggcauagcu..................',
       '.....................................................................aaggcaagaugucggcauagcA..................',
       '.....................................................................aaggcaagGugucggcauagcu..................',
       '.....................................................................aaggcaagaugucggcauagcCg.................',
       '.....................................................................aaggcaagaugucggAauagcug.................',
       '.....................................................................aaggcaagaugucggcauagcuA.................',
       '.....................................................................aaggcaagaugucggcauagcuC.................',
       '.....................................................................aaggcaagaugucggcauagcuU.................',
       '.....................................................................aaggcaagaugucggcauagcug.................',
       '.....................................................................Uaggcaagaugucggcauagcug.................',
       '.....................................................................aaggcaagaugucggcauagcugU................',
       '.....................................................................aaggcaagaugucggcauagcuga................',
       '.....................................................................Caggcaagaugucggcauagcuga................',
       '.....................................................................aaggcaagaugucggcauagcugG................',
       '.....................................................................aaggcaagaugucggcauagcugC................',
       '.....................................................................Gaggcaagaugucggcauagcuga................',
       '.....................................................................Uaggcaagaugucggcauagcuga................',
       '.....................................................................aaggcaagaugucggcauagcugUu...............',
       '.....................................................................aaggcaagaugucggcauagcugaA...............',
       '.....................................................................aaggcaagaugucggcauagcugau...............',
       '.....................................................................aaggcaagaugucggcauagcugUuu..............',
       '.....................................................................aaggcaagaugucggcauagcugauu..............',
       '......................................................................aggcaagaugucggcaua.....................',
       '......................................................................aggcaagaugucgUcaua.....................',
       '......................................................................aggcaagaugucggcauU.....................',
       '......................................................................aggcaagaugucgCcaua.....................',
       '......................................................................aggcaagaGgucggcauag....................',
       '......................................................................aggcaagaugucggcauCg....................',
       '......................................................................aggcaagaugucgUcauag....................',
       '......................................................................aggcaagaugucggcCuag....................',
       '......................................................................aCgcaagaugucggcauag....................',
       '......................................................................aggcaagaugucggcGuag....................',
       '......................................................................aggcaagaugucggcauaU....................',
       '......................................................................aggcaagaugucggGauag....................',
       '......................................................................agNcaagaugucggcauag....................',
       '......................................................................aggcaagaugucggcauGg....................',
       '......................................................................aggcaagaugucggcaGag....................',
       '......................................................................aggcaagGugucggcauag....................',
       '......................................................................aggcaagaugucggcUuag....................',
       '......................................................................aggcaaUaugucggcauag....................',
       '......................................................................Nggcaagaugucggcauag....................',
       '......................................................................aggcaagaAgucggcauag....................',
       '......................................................................aggcaagUugucggcauag....................',
       '......................................................................aggNaagaugucggcauag....................',
       '......................................................................aggcGagaugucggcauag....................',
       '......................................................................agUcaagaugucggcauag....................',
       '......................................................................aggcaagaugucAgcauag....................',
       '......................................................................aggcaagaugucggUauag....................',
       '......................................................................aggcaCgaugucggcauag....................',
       '......................................................................agCcaagaugucggcauag....................',
       '......................................................................aggcaagauguAggcauag....................',
       '......................................................................aNgcaagaugucggcauag....................',
       '......................................................................aggcaagaCgucggcauag....................',
       '......................................................................Gggcaagaugucggcauag....................',
       '......................................................................aggcaagauguUggcauag....................',
       '......................................................................aggcaagaugAcggcauag....................',
       '......................................................................aUgcaagaugucggcauag....................',
       '......................................................................aggcaagaugucUgcauag....................',
       '......................................................................aggcaagaugucggAauag....................',
       '......................................................................aggcaagaugucggcaCag....................',
       '......................................................................aggcaagaugucggcauag....................',
       '......................................................................aggcaagaugucggcaAag....................',
       '......................................................................aggAaagaugucggcauag....................',
       '......................................................................aggcCagaugucggcauag....................',
       '......................................................................aggcaagaugGcggcauag....................',
       '......................................................................aggcaGgaugucggcauag....................',
       '......................................................................aggcaagauAucggcauag....................',
       '......................................................................aggcaagaugCcggcauag....................',
       '......................................................................Uggcaagaugucggcauag....................',
       '......................................................................aggcaagaugucggcauaA....................',
       '......................................................................aggcaagaugucCgcauagc...................',
       '......................................................................aggcaagauguAggcauagc...................',
       '......................................................................aggcaagaugucggcauGgc...................',
       '......................................................................aggcaagaugucgAcauagc...................',
       '......................................................................aggcaagaugucggcauaUc...................',
       '......................................................................aggNaagaugucggcauagc...................',
       '......................................................................aggcaagaugucggcGuagc...................',
       '......................................................................agUcaagaugucggcauagc...................',
       '......................................................................aggGaagaugucggcauagc...................',
       '......................................................................Gggcaagaugucggcauagc...................',
       '......................................................................aggcaagaugucggcaAagc...................',
       '......................................................................Nggcaagaugucggcauagc...................',
       '......................................................................aggcaagaugGcggcauagc...................',
       '......................................................................aggcaagaugucAgcauagc...................',
       '......................................................................aggcaUgaugucggcauagc...................',
       '......................................................................aggcaagUugucggcauagc...................',
       '......................................................................aggcaagauAucggcauagc...................',
       '......................................................................aggcaagaugucggcauagG...................',
       '......................................................................aggcaagaugucggUauagc...................',
       '......................................................................aUgcaagaugucggcauagc...................',
       '......................................................................aggcaagaugucggcauaCc...................',
       '......................................................................aggcaagaugucggcauaAc...................',
       '......................................................................aggcaagaugucggcUuagc...................',
       '......................................................................aggcaagaugucggcauagc...................',
       '......................................................................agCcaagaugucggcauagc...................',
       '......................................................................aggcaGgaugucggcauagc...................',
       '......................................................................aggcaagaugucggcaCagc...................',
       '......................................................................agAcaagaugucggcauagc...................',
       '......................................................................aggcaagaCgucggcauagc...................',
       '......................................................................aggcaagaAgucggcauagc...................',
       '......................................................................aggcaaUaugucggcauagc...................',
       '......................................................................aggcaagaugucUgcauagc...................',
       '......................................................................aggcaaCaugucggcauagc...................',
       '......................................................................aggcaagaugucggcauCgc...................',
       '......................................................................aNgcaagaugucggcauagc...................',
       '......................................................................aggcaaAaugucggcauagc...................',
       '......................................................................aggcUagaugucggcauagc...................',
       '......................................................................aggcaagauguUggcauagc...................',
       '......................................................................aggcaagaugucggcaGagc...................',
       '......................................................................aggcaagGugucggcauagc...................',
       '......................................................................aggcaagaugucggcCuagc...................',
       '......................................................................aAgcaagaugucggcauagc...................',
       '......................................................................aggcaagCugucggcauagc...................',
       '......................................................................aggcaagaugucggGauagc...................',
       '......................................................................aggcaagauCucggcauagc...................',
       '......................................................................aggcaagaugucggcauagU...................',
       '......................................................................aggcaagaugAcggcauagc...................',
       '......................................................................aggcaagauUucggcauagc...................',
       '......................................................................aggcaagaugCcggcauagc...................',
       '......................................................................aggcCagaugucggcauagc...................',
       '......................................................................aggcaagaugucgUcauagc...................',
       '......................................................................aggcGagaugucggcauagc...................',
       '......................................................................aCgcaagaugucggcauagc...................',
       '......................................................................agNcaagaugucggcauagc...................',
       '......................................................................Uggcaagaugucggcauagc...................',
       '......................................................................aggcaagaugucgCcauagc...................',
       '......................................................................aggAaagaugucggcauagc...................',
       '......................................................................aggcaagaugucggcauagA...................',
       '......................................................................aggcaCgaugucggcauagc...................',
       '......................................................................aggUaagaugucggcauagc...................',
       '......................................................................aggcaagaugucggAauagc...................',
       '......................................................................Uggcaagaugucggcauagcu..................',
       '......................................................................aggUaagaugucggcauagcu..................',
       '......................................................................aggcaagaugucgAcauagcu..................',
       '......................................................................aggcaagaugucggcCuagcu..................',

In [142]:
# Extract 5' starting nucleotide (first nucleotide character) and its index for each alignment
five_prime_data = []

for i, aln in enumerate(test_alignments[1:]):  # skip consensus
    # Find index of first nucleotide (A, C, G, T, U, N - case insensitive)
    nucleotide_pattern = r'[ACGTUNacgtun]'
    match = re.search(nucleotide_pattern, aln)
    
    if match:
        idx = match.start()
        nucleotide = match.group().upper()
    else:
        # If no nucleotide found, record -1 and 'N'
        idx = -1
        nucleotide = 'N'
    
    # Get count from test_counts
    count = test_counts[i]
    location = test_alignments[0][idx] if idx != -1 and idx < len(test_alignments[0]) else 'N/A'

    five_prime_data.append({
        'five_prime_index': idx,
        'five_prime_nucleotide': nucleotide,
        'sequence_count': count,
        'alignment_location' : location
    })

# Create DataFrame
five_prime_df = pd.DataFrame(five_prime_data)
five_prime_df

     five_prime_index five_prime_nucleotide  sequence_count alignment_location
0                   9                     U               1                  f
1                  11                     U               1                  f
2                  26                     C               6                  S
3                  66                     G               7                  l
4                  67                     G               4                  l
..                ...                   ...             ...                ...
399                72                     G               3                  M
400                73                     C               2                  M
401                74                     A               2                  M
402                74                     A               3                  M
403                75                     A               1                  M

[404 rows x 4 columns]

In [147]:
# from scipy import stats
# import matplotlib.pyplot as plt

# # Weight five_prime_indices by sequence_counts
# weighted_indices = five_prime_df.loc[five_prime_df.index.repeat(five_prime_df['sequence_count']),'five_prime_index'].values

# # Create KDE plot with weighted indices
# kde = stats.gaussian_kde(weighted_indices)
# x_range = np.linspace(weighted_indices.min(), weighted_indices.max(), 200)

# plt.figure(figsize=(12, 5))
# plt.plot(x_range, kde(x_range), linewidth=2)
# plt.fill_between(x_range, kde(x_range), alpha=0.3)
# plt.xlabel('5\' Start Index')
# plt.ylabel('Density')
# plt.title('KDE Plot of 5\' Start Positions (Weighted by Sequence Count)')
# plt.grid(True, alpha=0.3)
# plt.show()

In [148]:
five_prime_df['sequence_count'].describe()

count       404.000000
mean       1071.029703
std       12178.139122
min           1.000000
25%           2.000000
50%           4.000000
75%          12.000000
max      217177.000000
Name: sequence_count, dtype: float64

In [181]:
five_prime_df.groupby('five_prime_index')['sequence_count'].sum().sort_values(ascending=False)

five_prime_index
70    427429
69      4133
71       863
72       210
68        34
66         7
26         6
74         5
67         4
73         2
9          1
11         1
75         1
Name: sequence_count, dtype: int64

In [192]:
def is_homogeneous(five_prime_index):
    """
    Improved homogeneity metrics for a given 5' start position.
    
    Returns:
    - max_prop: Proportion of reads at single most abundant position
    - top1/2/3_prop: Cumulative proportion in top N positions
    - normalized_entropy: Shannon entropy normalized by max entropy
    - gini_coefficient: Inequality measure (0=uniform, 1=concentrated)
    - n_distinct_positions: Number of different 5' start positions
    - coefficient_variation: Relative spread of counts
    - total_count: Total reads in window
    """
    # Determine the mature miRNA size range (typically 20-24 nt)
    alignment_position = five_prime_df.loc[five_prime_df['five_prime_index'] == five_prime_index, 'alignment_location'].iloc[0]
    if alignment_position == 'M' or alignment_position == 'S':
        miRNA_size = test_alignments[0].count(alignment_position)
    else:
        miRNA_size = 22  # default to 22nt if alignment location is not M or S
    
    
    min_idx = five_prime_index - miRNA_size
    max_idx = five_prime_index + miRNA_size
    
    # Filter reads within the tolerance window
    filtered = five_prime_df[
        (five_prime_df['five_prime_index'] >= min_idx) & 
        (five_prime_df['five_prime_index'] <= max_idx)
    ]
    if filtered.empty:
        return None
    
    counts = filtered['sequence_count'].values
    total = counts.sum()
    proportions = counts / total
    
    # Metric 1: Maximum proportion (reads at most abundant position)
    max_prop = proportions.max()
    # print entry or entries that achieve this max_prop
    max_positions = np.where(proportions == max_prop)[0]
    print("\nMAX_PROP entries in filtered window:")
    print(filtered.iloc[max_positions])
    
    # determine dominant nucleotide among filtered
    max_idx_in_filtered = np.argmax(counts)
    dominant_nucleotide = filtered.iloc[max_idx_in_filtered]['five_prime_nucleotide']
    
    # restrict to rows with dominant nucleotide
    nucleotide_filtered = filtered[filtered['five_prime_nucleotide'] == dominant_nucleotide]
    if nucleotide_filtered.empty:
        nucleotide_filtered = filtered
    
    # further restrict to exact five_prime_index for top-N metrics
    pos_filtered = nucleotide_filtered[nucleotide_filtered['five_prime_index'] == five_prime_index]
    use_filtered = pos_filtered if not pos_filtered.empty else nucleotide_filtered
    if pos_filtered.empty:
        print(f"WARNING: no reads exactly at position {five_prime_index}; using {len(use_filtered)} reads for top-N metrics")
    
    # compute proportions over the chosen subset
    sub_counts = use_filtered['sequence_count'].values
    sub_total = sub_counts.sum()
    sub_props = sub_counts / sub_total if sub_total > 0 else sub_counts
    
    # sort by these proportions
    sorted_idx = np.argsort(sub_props)[::-1]
    sorted_props = sub_props[sorted_idx]
    
    print(f"\n{'='*80}")
    print(f"5' Index: {five_prime_index} | Dominant Nucleotide: {dominant_nucleotide}")
    print(f"Rows at exact position: {len(pos_filtered)}; using {len(use_filtered)} rows for top-N")
    print(f"{'='*80}\n")
    
    # TOP 1
    top1_entries = use_filtered.iloc[sorted_idx[:1]]
    print("TOP1 entries:")
    print(top1_entries)
    top1_prop = sorted_props[0] if len(sorted_props) > 0 else 0
    print(f"TOP1 proportion: {top1_prop:.4f}\n")
    
    # TOP 2
    count_n = min(2, len(sorted_idx))
    top2_entries = use_filtered.iloc[sorted_idx[:count_n]]
    print("TOP2 entries:")
    print(top2_entries)
    top2_prop = sorted_props[:count_n].sum() if len(sorted_props) >= count_n else sorted_props.sum()
    print(f"TOP2 proportion: {top2_prop:.4f}\n")
    
    # TOP 3
    count_n = min(3, len(sorted_idx))
    top3_entries = use_filtered.iloc[sorted_idx[:count_n]]
    print("TOP3 entries:")
    print(top3_entries)
    top3_prop = sorted_props[:count_n].sum() if len(sorted_props) >= count_n else sorted_props.sum()
    print(f"TOP3 proportion: {top3_prop:.4f}\n")
    
    # Metric 3: Normalized Shannon entropy (still over full window)
    entropy = -np.sum(proportions * np.log2(proportions + 1e-10))
    max_entropy = np.log2(len(proportions))
    normalized_entropy = entropy / max_entropy if max_entropy > 0 else 0
    
    # Metric 4: Gini coefficient (0=uniform, 1=concentrated)
    sorted_counts = np.sort(counts)
    n = len(sorted_counts)
    gini = (2 * np.sum(np.arange(1, n+1) * sorted_counts)) / (n * sorted_counts.sum()) - (n + 1) / n
    
    # Metric 5: Number of distinct positions
    n_distinct_positions = len(filtered)
    
    # Metric 6: Coefficient of variation of counts
    cv = np.std(counts) / np.mean(counts) if np.mean(counts) > 0 else 0
    
    return {
        'star_or_mature' : alignment_position,
        'five_prime_index': five_prime_index,
        'max_prop': max_prop,
        'top1_prop': top1_prop,
        'top2_prop': top2_prop,
        'top3_prop': top3_prop,
        'normalized_entropy': normalized_entropy,
        'gini_coefficient': gini,
        'n_distinct_positions': n_distinct_positions,
        'coefficient_variation': cv,
        'total_count': total
    }

In [193]:
is_homogeneous(70)

MAX_PROP entries in filtered window:
     five_prime_index five_prime_nucleotide  sequence_count alignment_location
266                70                     U          217177                  M

================================================================================
5' Index: 70 | Dominant Nucleotide: U
Rows at exact position: 6; using 6 rows for top-N
================================================================================

TOP1 entries:
     five_prime_index five_prime_nucleotide  sequence_count alignment_location
266                70                     U          217177                  M
TOP1 proportion: 0.9841

TOP2 entries:
     five_prime_index five_prime_nucleotide  sequence_count alignment_location
266                70                     U          217177                  M
344                70                     U            3481                  M
TOP2 proportion: 0.9999

TOP3 entries:
     five_prime_index five_prime_nucleotide  sequence_count alignment_location
266                70                     U          217177                  M
344                70                     U            3481                  M
161                70                     U               8                  M
TOP3 proportion: 1.0000

{'star_or_mature': 'M',
 'five_prime_index': 70,
 'max_prop': np.float64(0.5019251747217395),
 'top1_prop': np.float64(0.9841441751708387),
 'top2_prop': np.float64(0.999918432453008),
 'top3_prop': np.float64(0.9999546846961156),
 'normalized_entropy': np.float64(0.2603068730666469),
 'gini_coefficient': np.float64(0.9877970965792633),
 'n_distinct_positions': 401,
 'coefficient_variation': np.float64(11.314054213195941),
 'total_count': np.int64(432688)}